include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
  errors:
    unused_import: ignore
    unnecessary_import: ignore
    deprecated_member_use: ignore
    avoid_print: ignore
    curly_braces_in_flow_control_structures: ignore

linter:

  rules:

