name: tailored_eats
description: "A new flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shimmer:
  url_launcher: ^6.3.1
  pin_code_fields:
  loading_animation_widget:
  http_parser: ^4.0.2
  mime: ^1.0.4
  flutter_screenutil: ^5.9.3
  flutter_animate:
  get:
  google_sign_in: ^6.3.0
  get_storage:
  connectivity_plus:
  flutter_svg:
  intl:
  cached_network_image:
  country_picker: ^2.0.27

  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/dummy/
