import 'package:get/get_navigation/src/routes/get_route.dart';

import '../bind/change_password_binding.dart';
import '../bind/consistency_binding.dart';
import '../bind/details_binding.dart';
import '../bind/faq_binding.dart';
import '../bind/find_frined_binding.dart';
import '../bind/forget_password_binding.dart';
import '../bind/friends_binding.dart';
import '../bind/friends_consistency_binding.dart';
import '../bind/goal_binding.dart';
import '../bind/home_binding.dart';
import '../bind/login_binding.dart';
import '../bind/navigation_binding.dart';
import '../bind/notification_binding.dart';
import '../bind/nutrition_binding.dart';
import '../bind/otp_binding.dart';
import '../bind/picture_progress_binding.dart';
import '../bind/policy_binding.dart';
import '../bind/preview_profile_binding.dart';
import '../bind/profile_binding.dart';
import '../bind/profile_creation_binding.dart';
import '../bind/register_binding.dart';
import '../bind/report_binding.dart';
import '../bind/reset_password_binding.dart';
import '../bind/setting_binding.dart';
import '../bind/splash_binding.dart';
import '../bind/support_binding.dart';
import '../bind/swap_binding.dart';
import '../bind/terms_binding.dart';
import '../bind/two_fa_binding.dart';
import '../bind/update_profile_binding.dart';
import '../bind/verification_binding.dart';
import '../bind/welcome_binding.dart';
import '../views/auth/forget_password/screen/forget_password_screen.dart';
import '../views/auth/login/screen/login_screen.dart';
import '../views/auth/otp/screen/otp_screen.dart';
import '../views/auth/register/screen/register_screen.dart';
import '../views/auth/reset_password/screen/reset_password_screen.dart';
import '../views/auth/two_fa/screen/two_fa_screen.dart';
import '../views/auth/verification/screen/verification_screen.dart';
import '../views/change_password/screen/change_password_screen.dart';
import '../views/consistency/screen/consistency_screen.dart';
import '../views/details/screen/details_screen.dart';
import '../views/faq/screen/faq_screen.dart';
import '../views/find_frined/screen/find_frined_screen.dart';
import '../views/friends/screen/friends_screen.dart';
import '../views/friends_consistency/screen/friends_consistency_screen.dart';
import '../views/goal/screen/goal_screen.dart';
import '../views/home/screen/home_screen.dart';
import '../views/navigation/screen/navigation_screen.dart';
import '../views/notification/screen/notification_screen.dart';
import '../views/nutrition/screen/nutrition_screen.dart';
import '../views/picture_progress/screen/picture_progress_screen.dart';
import '../views/policy/screen/policy_screen.dart';
import '../views/preview_profile/screen/preview_profile_screen.dart';
import '../views/profile/screen/profile_screen.dart';
import '../views/profile_creation/screen/profile_creation_screen.dart';
import '../views/report/screen/report_screen.dart';
import '../views/setting/screen/setting_screen.dart';
import '../views/splash/screen/splash_screen.dart';

import '../views/support/screen/support_screen.dart';
import '../views/swap/screen/swap_screen.dart';
import '../views/terms/screen/terms_screen.dart';
import '../views/update_profile/screen/update_profile_screen.dart';
import '../views/welcome/screen/welcome_screen.dart';

part 'pages.dart';

class Routes {
  static var list = RoutePageList.list;
static const find_frinedScreen = '/find_frinedScreen';
  static const pictureProgressScreen = '/picture_progressScreen';
  static const friendsConsistencyScreen = '/friends_consistencyScreen';
  static const previewProfileScreen = '/preview_profileScreen';
  static const reportScreen = '/reportScreen';
  static const policyScreen = '/policyScreen';
  static const termsScreen = '/termsScreen';
  static const faqScreen = '/faqScreen';
  static const supportScreen = '/supportScreen';
  static const changePasswordScreen = '/change_passwordScreen';
  static const settingScreen = '/settingScreen';
  static const notificationScreen = '/notificationScreen';
  static const updateProfileScreen = '/update_profileScreen';
  static const profileScreen = '/profileScreen';
  static const profileCreationScreen = '/profile_creationScreen';
  static const detailsScreen = '/detailsScreen';
  static const swapScreen = '/swapScreen';
  static const friendsScreen = '/friendsScreen';
  static const consistencyScreen = '/consistencyScreen';
  static const goalScreen = '/goalScreen';
  static const nutritionScreen = '/nutritionScreen';
  static const homeScreen = '/homeScreen';
  static const navigationScreen = '/navigationScreen';
  static const twoFaScreen = '/two_faScreen';
  static const registerScreen = '/registerScreen';
  static const otpScreen = '/otpScreen';
  static const resetPasswordScreen = '/reset_passwordScreen';
  static const verificationScreen = '/verificationScreen';
  static const forgetPasswordScreen = '/forget_passwordScreen';
  static const loginScreen = '/loginScreen';
  static const welcomeScreen = '/welcomeScreen';
  static const splashScreen = '/splashScreen';
}
